# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 60b369acedb25c959dc14fce672390336eb77c2f8ca7ad75ba00f0a08ef5f09ba3d553ce94cd5812a498baa7db2d4b346cc6cab5c976d7fd74badf5e1734c624

test:
  secret_key_base: 6e2cd9adf4dd4a9245d2583565d30ae8b7660946c58225c6693bbc937f731e5b0233fdc38b2caeb59c22c8ca6f4469c44feec05de992a2155202c7e1726c69bb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
